In [5]:
import pandas as pd
import numpy as np

In [6]:
pd.__version__

'2.2.2'

In [9]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [10]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [13]:
# how many records are in the dataset

df.shape

(2160, 12)

In [15]:
# How many laptop brands are presented in the dataset?
# Get unique brand names
unique_brands = df['Brand'].unique()

# Count the number of unique brands
total_brands = len(unique_brands)

print("Unique brands:", unique_brands)
print("Total number of different brands:", total_brands)


Unique brands: ['Asus' 'Alurin' 'MSI' 'HP' 'Lenovo' 'Medion' 'Acer' 'Apple' 'Razer'
 'Gigabyte' 'Dell' 'LG' 'Samsung' 'PcCom' 'Microsoft' 'Primux' 'Prixton'
 'Dynabook Toshiba' 'Thomson' 'Denver' 'Deep Gaming' 'Vant' 'Innjoo'
 'Jetwing' 'Millenium' 'Realme' 'Toshiba']
Total number of different brands: 27


In [17]:
df['Brand'].nunique()

27

In [19]:
# How many columns in the dataset have missing values?
# Count the number of missing values in each column
missing_values_count = df.isnull().sum()

# Count how many columns have missing values
columns_with_missing_values = missing_values_count[missing_values_count > 0]

# Display the number of columns with missing values
number_of_columns_with_missing_values = len(columns_with_missing_values)

print("Number of columns with missing values:", number_of_columns_with_missing_values)


Number of columns with missing values: 3


In [20]:
# What's the maximum final price of Dell notebooks in the dataset?
# Filter the DataFrame for rows where the 'Brand' is 'Dell'
dell_notebooks = df[df['Brand'] == 'Dell']

# Find the maximum value in the 'Final Price' column for Dell notebooks
max_final_price = dell_notebooks['Final Price'].max()

print("The maximum final price of Dell notebooks is:", max_final_price)


The maximum final price of Dell notebooks is: 3936.0


In [21]:
# Median value of Screen
#initial median of Screen column
df['Screen'].median()


15.6

In [22]:
# Next, calculate the most frequent value of the same Screen column.
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [27]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['Screen'] = df['Screen'].fillna(15.6)

df['Screen'].median()




15.6

In [28]:
# Sum of weights

injoo_laptops = df[df['Brand'] == 'Innjoo']

In [30]:
# Select only columns RAM, Storage, Screen
X = injoo_laptops[['RAM', 'Storage', 'Screen']]

In [34]:
# Get the underlying NumPy array. Let's call it X
X = X.to_numpy()
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [35]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

# Compute the matrix-matrix multiplication between the transpose of X and X
XTX = np.dot(X.T, X)

# Alternatively, using the @ operator for matrix multiplication
# XTX = X.T @ X

# Display the result
print("XTX (X transpose times X):\n", XTX)


XTX (X transpose times X):
 [[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [36]:
# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Display the result
print("Inverse of XTX:\n", XTX_inv)

Inverse of XTX:
 [[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [37]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]

y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Display the array
print("Array y:", y)

Array y: [1100 1300  800  900 1000 1100]


In [38]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

# inverse of XTX multiplied by transpose
XTX_inv_XT = np.dot(XTX_inv, X.T)

#  Multiply the result by y to get w
w = np.dot(XTX_inv_XT, y)

# Display the result
print("The result w is:\n", w)

The result w is:
 [45.58076606  0.42783519 45.29127938]


In [39]:
# What's the sum of all the elements of the result?
sum_w = np.sum(w)

print(sum_w)

91.29988062995815
